platform: linux

image_resource:
  type: docker-image
  source:  
    repository: ansible/ubuntu14.04-ansible
  
inputs:
- name: project-repository
  path: .
run:
  path: bash
  args: [tests/test.sh] 
