platform: linux

image_resource:
  type: docker-image
  source:  
    repository: ansible/ansible
    tag: ubuntu1204 
  
inputs:
- name: project-repository
  path: .
run:
  path: ansible
  args: [--version]
