platform: linux

image_resource:
  type: docker-image
  source:  
    repository: ansible/ubuntu14.04-ansible
  
inputs:
- name: project-repository
  path: .
run:
  path: ansible-playbook
  args: [-i tests/inventory tests/test.yml --syntax-check ] 
