platform: linux

image_resource:
  type: docker-image
  source:  
    repository: ansible/ubuntu14.04-ansible
  
inputs:
- name: project-repository
  path: .
run:
  #path: ansible-playbook
  #args: [/etc/ansible/roles/unir.kernel/tests/test.yml] 
  path: ansible-playbook 
  args: [ansible-docker-role/tests/test -i inventory]
