resources:
- name: project-repository
  type: git
  source:
    uri: https://github.com/Quirio/ansible-docker-role.git
    branch: master

jobs:
- name: building 
  public: true
  plan:
  - get: project-repository
  - task: hello-world
    file: "tasks/main.yml"  

