jobs:
- name: docker-ansible-rol 
  public: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source: { repository: ubuntu}
      run:
        path: echo
        args: [hello world]
  - task: goodbye
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source: { repository: ubuntu}
      run:
        path: echo
        args: [goodbye]


